experiment_name: gaussian
random_seed: 1998
head_type: gaussian
dataset:
  type: image
  spec: rotated_mnist
training:
  accelerator: cpu
  batch_size: 32
  chkp_dir: chkp/rotated-mnist
  chkp_freq: 50
  num_epochs: 50
  optimizer:
    type: adam_w
    kwargs:
      lr: 0.001
      weight_decay: 0.00001
  lr_scheduler:
    type: cosine_annealing
    kwargs:
      T_max: 50
      eta_min: 0
      last_epoch: -1
evaluation:
  num_trials: 1
  log_dir: logs/rotated-mnist
