from .aaf_datamodule import AAFDataModule
from .coco_people_datamodule import COCOPeopleDataModule
from .coco_people_datamodule import OodCocoPeopleDataModule
from .eva_datamodule import EVADataModule
from .tabular_data_module import TabularDataModule
