experiment_name: eva_natural_gaussian
random_seed: 1998
head_type: natural_gaussian
dataset:
  type: image
  spec: eva
batch_size: 4
accelerator: cpu
log_dir: logs/natural_gaussian_results
model_ckpt_path: chkp/eva_natural_gaussian/version_0/best_loss.ckpt
