experiment_name: name_of_experiment_here
random_seed: 1998
head_type: gaussian
dataset:
  type: image
  spec: coco_people
batch_size: 4
accelerator: cpu
log_dir: path/to/log/dir
model_ckpt_path: path/to/model.ckpt
