experiment_name: fg_net_seitzer
random_seed: 1998
head_type: gaussian
dataset:
  type: image
  spec: fg_net
training:
  accelerator: gpu
  batch_size: 32
  chkp_dir: chkp
  chkp_freq: 100
  num_epochs: 100
  optimizer:
    type: adam_w
    kwargs:
      lr: 0.001
      weight_decay: 0.00001
  beta_scheduler:
    type: cosine_annealing
    kwargs:
      beta_0: 0.5
      beta_1: 0.5
      last_epoch: -1
  lr_scheduler:
    type: cosine_annealing
    kwargs:
      T_max: 100
      eta_min: 0
      last_epoch: -1
evaluation:
  num_trials: 1
  log_dir: logs
