experiment_name: aaf
random_seed: 1998
head_type: gaussian
dataset:
  type: image
  spec: aaf
training:
  accelerator: gpu
  batch_size: 64
  chkp_dir: chkp
  chkp_freq: 6
  num_epochs: 5
  precision: bf16-mixed
  optimizer:
    type: adam_w
    kwargs:
      lr: 0.001
      weight_decay: 0.00001
  lr_scheduler:
    type: cosine_annealing
    kwargs:
      T_max: 30
      eta_min: 0
      last_epoch: -1
evaluation:
  num_trials: 1
  log_dir: logs
