experiment_name: mnist_gaussian
random_seed: 1998
head_type: gaussian
dataset:
  type: image
  spec: mnist
training:
  accelerator: gpu
  batch_size: 8
  chkp_dir: /home/porter/spencer/code/probcal/training/chkp/mnist_gaussian
  chkp_freq: 10
  num_epochs: 20
  optimizer:
    type: adam_w
    kwargs:
      lr: 0.001
      weight_decay: 0.00001
  lr_scheduler:
    type: cosine_annealing
    kwargs:
      T_max: 50
      eta_min: 0
      last_epoch: -1
evaluation:
  num_trials: 2
  log_dir: /home/porter/spencer/code/deep_uncertainty/logs/extra