experiment_name: dispersed_waves_gaussian
random_seed: 1998
head_type: gaussian
dataset:
  type: tabular
  path: data/dispersed_waves/dispersed_waves.npz
  input_dim: 1
training:
  accelerator: cpu
  batch_size: 32
  chkp_dir: weights
  chkp_freq: 50
  num_epochs: 200
  optimizer:
    type: adam_w
    kwargs:
      lr: 0.001
      weight_decay: 0.00001
  lr_scheduler:
    type: cosine_annealing
    kwargs:
      T_max: 200
      eta_min: 0
      last_epoch: -1
evaluation:
  num_trials: 1
  log_dir: logs
