experiment_name: coco_seitzer
random_seed: 1998
head_type: gaussian
dataset:
  type: image
  spec: coco_people
batch_size: 4
accelerator: cuda
log_dir: logs/coco/seitzer_results
model_ckpt_path: chkp/coco/seitzer/best_mae.ckpt
mcmd_num_trials: 5
