experiment_name: coco_poisson
random_seed: 1998
head_type: poisson
dataset:
  type: image
  spec: coco_people
batch_size: 4
accelerator: cuda
log_dir: logs/coco/poisson_results
model_ckpt_path: chkp/coco/poisson/best_loss.ckpt
mcmd_num_trials: 1
