experiment_name: coco_stirn
random_seed: 1998
head_type: faithful_gaussian
dataset:
  type: image
  spec: coco_people
batch_size: 4
accelerator: cuda
log_dir: logs/coco/stirn_results
model_ckpt_path: chkp/coco/stirn/best_loss.ckpt
mcmd_num_trials: 5
