experiment_name: coco_nbinom
random_seed: 1998
head_type: negative_binomial
dataset:
  type: image
  spec: coco_people
batch_size: 4
accelerator: gpu
log_dir: logs/coco/nbinom_results
model_ckpt_path: chkp/coco/nbinom/best_loss.ckpt
