experiment_name: coco_ddpn
random_seed: 1998
head_type: double_poisson
dataset:
  type: image
  spec: coco_people
batch_size: 4
accelerator: cuda
log_dir: logs/coco/ddpn_results
model_ckpt_path: chkp/coco/ddpn/best_loss.ckpt
mcmd_num_trials: 5
